
// This file can be generated by `npx supabase gen types typescript --project-id oyhekwvfvmuzlodqqmfm > src/lib/database.types.ts`
import type { Database } from './database.types';

export type MenuItem = Database['public']['Tables']['menu_items']['Row'];
export type MenuCategory = {
  id: string;
  name: string;
  items: MenuItem[];
};

export interface CartItem {
  menuItem: MenuItem;
  quantity: number;
}

export type Order = Database['public']['Tables']['orders']['Row'];
export type OrderItem = Database['public']['Tables']['order_items']['Row'] & { menu_item: MenuItem };

export type OrderStatus = "awaiting_payment" | "in_preparation" | "delivered" | "cancelled";
export type PaymentMethod = "Stripe" | "Espèces";

export type FullOrder = Order & {
    order_items: OrderItem[]
};

export type Invoice = Database['public']['Tables']['invoices']['Row'];
export type InvoiceStatus = "draft" | "sent" | "paid";

export type FullInvoice = Invoice & {
    order: FullOrder;
};
